### ISSUE TITLE
parse function is broken

### ISSUE THREAD

**Issue by DavertMik** [tunnckoCore/opensource#105]
The last release of parse function is broken as it is missing `arrify` package which is in dev dependencies, while it should be in main dependencies. 
We had to urgently update our package to add it.

**Comment by tunnckoCore** [comment]
Thanks for the report. I'll look into it. 

It's in devDeps, because we bundle/resolve external deps into the final build. But obviously something gone wrong.

**Comment by DavertMik** [comment]
Thanks!
We included `arrify` and made a new version.

**Comment by tunnckoCore** [comment]
Might be fixed in `5.5.1`
