### ISSUE TITLE
koa-better-body example

### ISSUE THREAD

**Issue by Coada** [tunnckoCore/opensource#116]
Hi,

I ended up finding `koa-better-body` as it allows setting my own Formidable object, which `koa-body` does not seem to allow. My project also uses `@koa/router`.

The `koa-better-body` example with the router however does not seem to work? I am getting:

```
var app = require('koa')();
                        ^

TypeError: Class constructor Application cannot be invoked without 'new'
```

**Comment by tunnckoCore** [comment]
It's because it most probably shows that exacmple for the Koa prior v2 when Koa became a Class.

```js
var Koa = require('koa');
var app = new Koa();
```

**Comment by tunnckoCore** [comment]
`@koa/router` is fork of the previously most used `koa-router`.

Both `koa` v2 and `@koa/router` export default as class. So the example would be

```js
const Koa = require('koa');
const body = require('koa-better-body');
const Router = require('@koa/router');

const app = new Koa();
const router = new Router()
```
