### ISSUE TITLE
parse-commit-message missing build contents in distribution

### ISSUE THREAD

**Issue by cdaringe** [tunnckoCore/opensource#147]
#### Support plan

- _which support plan is this issue covered by?_ (e.g. Community, Sponsor, or
  Enterprise): Community
- _is this issue currently blocking your project?_ (yes/no): yes
- _is this issue affecting a production system?_ (yes/no): no

#### Context

- _node version_: 13
- _module version_: 4.x (all canary versions)
- _environment_ (e.g. node, browser, native): node
- _used with_ (i.e. popular names of modules): semantic-pull-request
- _any other relevant information_: ref: https://github.com/zeke/semantic-pull-requests/pull/75#issuecomment-634898146

#### What are you trying to achieve or the steps to reproduce?

`require('parse-commit-message')` fails--essential JS assets are missing from the distribution. see link above

#### What was the result you got?

MODULE_NOT_FOUND

#### What result did you expect?

no MODULE_NOT_FOUND error

**Comment by tunnckoCore** [comment]
Aaaah, damn. Sorry about that...

I'm not sure it's "all canary versions" as you stated. I remember there was some working ones.

**Comment by tunnckoCore** [comment]
closing

just released updated source code to TypeScript, supporting CJS/ESM, TypeScript & Types
