### ISSUE TITLE
npm install removes raw-body dependencies from koa-body-parsers triggering error

### ISSUE THREAD

**Issue by jonathanasquier** [tunnckoCore/opensource#35]
This is a situation we have been fighting with for quite some time, and we keep checking out this block from our package-locks which is obviously very hacky

We use node 10.13.0 and npm 6.4.1 with docker in all our apis, and all of them use koa-better-body
We have been unable to explain why sometimes the raw-body dependency is added, and why sometimes it is removed

which triggers `Cannot find module 'raw-body'`

```diff
+        "koa-body-parsers": {
+          "version": "git+https://github.com/tunnckoCore/body-parsers.git#b515504ef0bfe3e04aa3dd13502d3d90c2d60956",
+          "from": "git+https://github.com/tunnckoCore/body-parsers.git#b515504ef0bfe3e04aa3dd13502d3d90c2d60956"
         }
       }
     },
-    "koa-body-parsers": {
-      "version": "git+https://github.com/tunnckoCore/body-parsers.git#b515504ef0bfe3e04aa3dd13502d3d90c2d60956",
-      "from": "git+https://github.com/tunnckoCore/body-parsers.git",
-      "requires": {
-        "raw-body": "^2.1.0"
-      }
-    },
// removes the whole raw-body block
```
The koa-better body version is set to ^3.0.4
Any advice is welcome!

Thank you! :)

**Comment by tunnckoCore** [comment]
@jonathanasquier is it fixed with later versions?

**Comment by jonathanasquier** [comment]
3.3.9 fixes it, i wish it was based on a proper release of koa-body-parsers rather than patch-1 though.
Thank you!

**Comment by tunnckoCore** [comment]
@jonathanasquier true. I don't get the time to move it to its regular release, a lot has changed since this patch...
