### ISSUE TITLE
npm install koa-better-body failing this morning

### ISSUE THREAD

**Issue by MichaelCation** [tunnckoCore/opensource#58]
When I ran "npm install koa-better-body" on a clean machine this morning it failed with "npm ERR! enoent undefined ls-remote -h -t https://github.com/tunnckoCore/body-parsers.git"

Perhaps "body-parsers.git" should be "koa-body-parsers.git" instead?

**Comment by tunnckoCore** [comment]
Oh, sorry for the delay. I was offline whole week.

I'll check.

**Comment by tunnckoCore** [comment]
No, it's correct. https://github.com/tunnckoCore/body-parsers it's an old fork... 
The thing is I'm not sure why it was and what is changed between the original and the fork.

**Comment by tunnckoCore** [comment]
Yea, it seems we can just switch to the original one.

**Comment by tunnckoCore** [comment]
Oh, I remember why is the fork. The main reason. 

https://github.com/koajs/body-parsers/issues/19
https://github.com/koajs/body-parsers/issues/20

So, suggested a PR there https://github.com/koajs/body-parsers/issues/19

**Comment by tunnckoCore** [comment]
@MichaelCation probably your server where you are installing doesn't have git?

**Comment by tunnckoCore** [comment]
Probably similar to #36. We'll wait response. :)

**Comment by tunnckoCore** [comment]
@MichaelCation is it fixed? Try `v3.1+`, best `3.1.13`

**Comment by tunnckoCore** [comment]
Closing. Please try newer versions or report again with new issue here.
