### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by ramya-Senthamaraikannan** [tunnckoCore/opensource#70]
am trying to install orientjs in my project which in-turn requires parse-function() npm and it throws babel error

**Comment by louis-bertrand** [comment]
hi,
quick fix: add **"parse-function": "5.2.11"** in your package.json

**Comment by tunnckoCore** [comment]
Ah! Yea... Sorry, @louis-bertrand, @ramya-Senthamaraikannan @cviejo @Vincentmarrec, @DavertMik!

I'm going to publish now.

**Comment by tunnckoCore** [comment]
Just published `5.4.0`. Should be working.

**Comment by tunnckoCore** [comment]
Aaaah

**Comment by tunnckoCore** [comment]
Okay. Very sorry. Now it should work, finally.

Soon expect v6 written in TypeScript.
