### ISSUE TITLE
Published package does not include TS definitions

### ISSUE THREAD

**Issue by neezer** [tunnckoCore/opensource#87]
`typings` is defined in `package.json`, but the file it points to is not present in the distributed package:

https://unpkg.com/browse/koa-better-body@3.1.13/package.json

```
  "typings": "dist/typings/index.d.ts",
```

```
❯ npm pack koa-better-body
npm notice 
npm notice 📦  koa-better-body@3.1.13
npm notice === Tarball Contents === 
npm notice 619B   dist/main/index.js      
npm notice 477B   dist/module/index.js    
npm notice 4.9kB  dist/main/utils.js      
npm notice 4.4kB  dist/module/utils.js    
npm notice 2.5kB  package.json            
npm notice 2.2kB  dist/main/index.js.map  
npm notice 2.3kB  dist/module/index.js.map
npm notice 13.1kB dist/main/utils.js.map  
npm notice 13.3kB dist/module/utils.js.map
npm notice 19.0kB CHANGELOG.md            
npm notice 24.1kB README.md               
npm notice === Tarball Details === 
npm notice name:          koa-better-body                         
npm notice version:       3.1.13                                  
npm notice filename:      koa-better-body-3.1.13.tgz              
npm notice package size:  20.9 kB                                 
npm notice unpacked size: 86.9 kB                                 
npm notice shasum:        eab742745401eff70b8069b29c284df87be2c1a6
npm notice integrity:     sha512-744Ay3hXDobRS[...]xC4sWJbErFndg==
npm notice total files:   11                                      
npm notice 
koa-better-body-3.1.13.tgz
```

In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39451, `@types/koa-better-body` was deprecated (12 days ago), so this missing typings file is making this package unbuildable with TypeScript.

**Comment by tunnckoCore** [comment]
Doh... problems problems problems. Why are they doing this? Or at least can mention me...

I recently tend to add that field but not yet having a typescript definitions. It's work in progress repo and situation. I'm slowly migration everything here so... it's a lot of work to get everything working correctly and seamlessly.

Thanks for the report.

**Comment by tunnckoCore** [comment]
@neezer is it okay now?

**Comment by neezer** [comment]
> I recently tend to add that field but not yet having a typescript definitions.

I would discourage this. There are many tools in the TS ecosystem that switch behavior on the `typings` field, so providing that field without the backing file is much more likely to cause problems than simply omitting the field until you get the definitions in place. 

I would track what is in essence a "todo" in a GitHub issue, or README, or anywhere else that is documentation-oriented and not used programmatically. My two cents.

> is it okay now? Changes there are rolled back.

I'll check and report back.

**Comment by tunnckoCore** [comment]
Yup, sure. I'll take that in mind and update.

**Comment by maximedupre** [comment]
@tunnckoCore Do you plan on providing the type definitions in the near future?

Cheers!

**Comment by tunnckoCore** [comment]
yea in the near future, after 10th i'm returning from holidays

**Comment by maximedupre** [comment]
@tunnckoCore Got it! Is there an available type def file somewhere that I can link manually into my project? As I recall, I had no problem before the repo changed place, so my guess is that the file exist, but I can't find it in the old repo. Happy holidays sir!

**Comment by tunnckoCore** [comment]
Hmmm, no, I dont think... oh, wait I think there is typedef in definitely-typed repo and so a `@types` package. Only the versions doesn't match. Intentionally. I think it 3.0.24 or 25.

**Comment by maximedupre** [comment]
`npm i --save @types/koa-better-body@3.0.0` :D
